[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
socialtipping = "DafEaM7Us45XUh4NPz5AgkRWoicgwcXEnLsYt4zgLJou"

[programs.devnet]
socialtipping = "DafEaM7Us45XUh4NPz5AgkRWoicgwcXEnLsYt4zgLJou"

[programs.mainnet]
socialtipping = "DafEaM7Us45XUh4NPz5AgkRWoicgwcXEnLsYt4zgLJou"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
